name: Build and test
on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        type: [debug, release]
    runs-on: ${{ matrix.os }}
    steps:

    - name: checkout code
      uses: actions/checkout@v4

    - name: install black
      run: pip install black

    - name: check format
      run: python3 scripts/format.py --path src --check

    - name: install xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: configure xmake
      run: xmake f -cv

    - name: build with xmake
      run: xmake build

    - name: install to INFINI_ROOT
      if: matrix.os != 'windows-latest'
      run: xmake install

    - name: build infiniop-test
      if: matrix.os != 'windows-latest'
      run: xmake build infiniop-test

    - name: python test
      if: matrix.os != 'windows-latest'
      run: |
        pip install torch
        LD_LIBRARY_PATH=$HOME/.infini/lib python test/infiniop/matmul.py --cpu
        LD_LIBRARY_PATH=$HOME/.infini/lib python test/infiniop/rms_norm.py --cpu
        LD_LIBRARY_PATH=$HOME/.infini/lib python test/infiniop/random_sample.py --cpu
